-- AlterTable
ALTER TABLE `Permission` MODIFY `permission` ENUM('MESSAGE_SEND', 'MESSAGE_DELETE', 'CHANNEL_CREATE', 'CHANNEL_READ', 'CHANNEL_UPDATE', 'CHANNEL_DELETE', 'ROLE_CREATE', 'ROLE_READ', 'ROLE_UPDATE', 'ROLE_DELETE', 'ROLE_ASSIGN', 'SERVER_UPDATE') NOT NULL;
